markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "run with you"
markdown: rdiscount

author: "sheng"
atom-baseurl: "https://websay.me"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
