markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "医生生病了"
markdown: rdiscount

author: "sheng"


navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
