markdown: rdiscount
highlighter: pygments
permalink: /:title.html
name: "医生生病了"
markdown: rdiscount

author: "<a href='/' style='color:#bb2222'>SHENG</a> KEEP CALM AND CODING."
atom-baseurl: "http://websay.me"
